site_name: Stellio Context Broker
site_url: https://stellio.readthedocs.org
repo_url: https://github.com/stellio-hub/stellio-docs
site_description: Stellio Context Broker Documentation
docs_dir: docs
site_dir: html
edit_uri: edit/master/docs
markdown_extensions: [toc,fenced_code]
use_directory_urls: false
theme: readthedocs
extra_css: ["https://www.fiware.org/style/fiware_readthedocs.css", "https://www.fiware.org/style/fiware_readthedocs_core.css"]
# google_analytics: ['UA-83236805-1', 'fiware-orion.readthedocs.io']
nav:
  - Home: index.md
  - Getting Started: 'quick_start_guide.md'
  - API Walkthrough: 'API_walkthrough.md'
  - User & Programmers Manual:
      - Authentication and authorization: 'user/authentication_and_authorization.md'
      - Visualizing the graph: 'user/visualizing_graph.md'
      - Data model: 'user/data_model.md'
  - Installation & Administration Manual:
      - Production deployment: 'admin/production_deployment.md'
      - Monitoring and logging: 'admin/monitoring_and_logging.md'
      - Upgrading:
        - General notes: 'admin/upgrading_general_notes.md'
        - Upgrading to 0.7.0: 'admin/upgrading_to_0.7.0.md'
